frida/frida-core

src/darwin/mapper.c
Requires the new `gum_arm64_writer_put_add_reg_reg_reg` function from https://github.com/frida/frida-gum/pull/17
=> Fix arm and arm64 mapping

lib/pipe/pipe-windows.c
- Removed a bit of complexity with use of ConvertStringSecurityDescriptorToSecurityDescriptor
- Migrated DACL ACE for Everyone
- Added DACL ACE for AppContainer
- Added SACL ACE for Low Integrity
Security review needed.
=> Update security attributes on named pipe

lib/pipe/pipe-windows.c
Windows XP-Windows 10 xplat ConvertStringSecurityDescriptorToSecurityDescriptor support, fixing
regression introduced (see #54)
=> Expanded update of security attributes on named pipe (fixes #54)

src/darwin/frida-helper-backend-glue.m
Place a second hardware breakpoint at the end of dylb's `ImageLoader::recursiveInitialization` to let it release the spinlock and notify the end of libSystem initialization. This is done reusing the live disassembly tool. dyld is found in memory like before, going back from main thread's instruction pointer.
=> Fix deadlock caused by breaking inside libSystem initialization

src/darwin/frida-helper-backend-glue.m
- Get hold of the main thread to read its instruction pointer, which will
tell us where dyld is in memory.
- Walk backwards to find dyld's Mach-O header.
- Walk its symbols and find a function that's called at a point where the
process is sufficiently initialized to load frida-agent, but early enough
so that app's initializer still didn't run. In this case we choose
`dyld::initializeMainExecutable()`. At the beginning of this function dyld is
initialized but libSystem is still missing.
- Set a hardware breakpoint at the beginning of this function.
- Swap out the thread's exception ports with our own.
- Resume the task.
- Wait until we get a message on our exception port, meaning our breakpoint
was hit.
- Hijack thread's instruction pointer to call `dlopen("/usr/lib/libSystem.B.dylib")` …
=> Rewrite early instrumentation using thread hijacking

lib/gadget/gadget.vala
=> Add support for bytecode loading in frida-gadget

src/darwin/agent/launchd.js, src/darwin/frida-helper-backend.vala, src/darwin/policy-softener.vala, src/meson.build
=> Add support for Electra on iOS

lib/agent/syscall-linux-mips.S
This is to complete [#195](https://github.com/frida/frida-core/pull/195). I missed a register correction.
=> Fix MIPS regressions

src/darwin/frida-helper-backend-glue.m
Apparently task_info fails randomly with “invalid argument” (and sometimes “mig server died”) because we’re calling it too early in task’s lifetime. It will now retry at most 3 times before giving up.
=> Add retry logic around task_info call

src/darwin/darwin-host-session.vala
- avoid trying to deliver crash reports to dying xpcproxies
- bump all delivery timeouts which aren’t still expired at the time a crash report process is detected, in case it takes too much time to be attached and instrumented (especially when recovering from memory pressure after a jetsam event)
=> Improve iOS crash reporting

lib/payload/libc-shim.c
We previously relied on the libc++ destructors only calling free() but
not actually touching the memory before doing so, and this assumption
broke once the TLS emulation entered the picture.
=> Fix crash on unload with latest NDKs on Android/ARM

src/darwin/frida-helper-process.vala, src/darwin/fruitjector.vala, src/linux/frida-helper-process.vala, src/linux/linjector.vala, src/linux/linux-host-session.vala, src/windows/windows-host-session.vala, src/windows/winjector.vala
=> Handle failure to create temporary files

inject/inject.vala
./frida-inject -f com.android.browser -s hello.js
=> add spawn file argument to frida-inject

src/linux/agent/system-server.js
allow using the activity param in case the app doesn't have a launcher activity
=> improve spawn in Android apps

src/darwin/policy-softener-glue.c
leftover from https://github.com/frida/frida-core/pull/291
=> Avoid calling substitute_setup_process on null port

src/darwin/frida-helper-process.vala
In this way there’s no need to install a `SIGCHLD` handler which could conflict with others already installed in the process, causing issues for example with NodeJS and its `child_process` logic.
=> Daemonize helper process on Darwin

src/fruity/dtx.vala
Exactly like debugserver, now it uses a secure endpoint.
=> Add support for iOS 14.x secure DTX

src/darwin/frida-helper-backend-glue.m
It happens randomly that after hitting a single-step breakpoint, even if we disable it and continue, it still hits once.
(especially visible on iOS 14.x with unc0ver 6.x)
This change detects and reacts to this condition.
=> Workaround single-step delay

lib/payload/libc-shim.c
Doesn't seem to fix https://github.com/frida/frida/issues/1647 entirely, unless I'm still building it out of date by accident..
=> Fix build for new Xcode.

lib/gadget/gadget.vala
These parameters are then "reflected" into app's info under `parameters.parameters`
=> Add interaction.parameters to gadget in connect mode

src/fruity/usbmux.vala
The same idea as for Android (https://github.com/frida/frida-core/pull/399)
https://github.com/frida/frida-core/blob/c1424f12b53bac48103f91ce642679000cec6c33/src/droidy/droidy-client.vala#L800-L816
ref: https://github.com/frida/frida/issues/1941
=> fruity: Use env variables to find usbmuxd

lib/agent/meson.build, lib/gadget/meson.build, meson.build, src/compiler/compiler.vala, src/linux/linux-host-session.vala
=> Fallback to default runtime for system server agent

meson.build
fix #451 
fail early when required functions are missing
=> Check required functions

src/darwin/frida-helper-backend-glue.m
introduced in https://github.com/frida/frida-core/commit/a081f8ff2211dbb0ae074b54cf9fb3b2f87c9034
=> fix memory leak in fallback kill code

src/darwin/frida-helper-backend-glue.m
Seems like new mangling of ProcessInfo
```
nm dyld.17b3 | grep ProcessInfo
00000001dd364b48 d __ZL12sProcessInfo
00000001a8619bb4 t __ZN5dyld423ExternallyViewableState23storeProcessInfoPointerEPP20dyld_all_image_infos
```
=> Fix spawn issues IOS 17 beta3

server/server.vala, src/system.vala
I have no clue about vala, so if there are things I should have done differently, I'd love to hear them :)
=> server: use sysroot for temporary files on rootless

src/compiler/package-lock.json, src/compiler/package.json
=> Bump rollup to ^4.1.5

lib/gadget/gadget.vala
To allow Gum making better decisions taking into account its own promised lifetime (depends on https://github.com/frida/frida-gum/pull/768)
=> gadget: Move TeardownRequirement parameter to Gum

src/darwin/frida-helper-backend-glue.m
=> Work around thread_set_state_allowed crash

inject/inject.vala, lib/base/rpc.vala, lib/gadget/gadget.vala, lib/payload/script-engine.vala, src/barebone/script.vala, src/compiler/compiler.vala, src/host-session-service.vala
Please see https://github.com/frida/frida-gum/pull/798
=> Changes to support binary data on stdin and stdout

src/fruity/injector.vala
added a few new dyld symbols there updated in iOS 18.4
=> Fix #1153 Update injector dyld init detection for iOS 18.4
