frida/frida-core

src/generate-api.py

Fix for python3:
Traceback (most recent call last):
File "../../../../frida-core/src/generate-api.py", line 180, in <module>
output_deps_file.write("glib-2.0")
TypeError: 'str' does not support the buffer interface mode
Another fix would be output_deps_file.write("glib-2.0".decode("UTF-8")) for all strings.

Open the files in text mode, not binary mode

---

src/qnx/qinjector-glue.c
src/qnx/qinjector.vala

This fixes the stream seek which was unintentionally changed to SeekType.END in an earlier commit.
It also increases the stack size of the injected stack to 2Mb so that v8 has some room to breath.

Fix stream seek and increase stack size of injected thread

---

src/qnx/qinjector.vala

Fix qinjector so that it waits until the injected thread sends some data
on the pipe before waiting for the EOF which indicates that the injected
thread is done.

Fix qinjector/injected thread race condition

---

src/qnx/qinjector-glue.c

Otherwise, trying to dealloc will fail with an assertion, killing frida-server.

Check to see that the target is still alive before deallocing

---

src/linux/system-linux.c

```
../../../../frida-core/src/linux/system-linux.c: In function 'frida_system_enumerate_applications':
../../../../frida-core/src/linux/system-linux.c:69:10: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
info = &g_array_index (applications, FridaHostProcessInfo, applications->len - 1);
^
../../../../frida-core/src/linux/system-linux.c:81:10: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
return g_array_free (applications, FALSE);
^
../../../../frida-core/src/linux/system-linux.c: In function 'frida_system_enumerate_processes':
../../../../frida-core/src/linux/system-linux.c:139:10: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
return g_array_free (processes, FALSE);
```

Fix for compiler messages

---

src/windows/windows-host-session-glue.c

DEBUG_* flags added to skip Image File Execution Options (IFEO) lookup second time around. Allows use of frida in IFEO scenarios.

Add CreateProcessW flags to prevent IFEO loop

---

frida-core.vcxproj
frida-core.vcxproj.filters
lib/pipe/frida-pipe-32.vcxproj
lib/pipe/frida-pipe-32.vcxproj.filters
lib/pipe/frida-pipe-64.vcxproj
lib/pipe/frida-pipe-64.vcxproj.filters
lib/pipe/pipe-helpers.c
lib/pipe/pipe-helpers.h
lib/pipe/pipe-windows.c
src/windows/access-helpers.c
src/windows/access-helpers.h
src/windows/winjector-glue.c
src/windows/winjector.vala

Alters temporary directory ACL, adding AppContainer ACE (with child inheritance for files and folders within) to facilitate Windows Store/Universal app scenarios
There's some minor OS versioning duplication, but this will eventually go away after Windows SDK/VS toolset is updated and VersionHelpers brought in.

Changes to support AppContainer ACL on temporary directory/files within

---

lib/agent/agent-glue.c

Keep a handle to libdl.so.2 so that it is never unloaded even when
libfrida-agent.so unloads in a process that did not previously have
libdl loaded.
This is to prevent a bug which was encountered where libdl tries to
perform a TLS key destructor after the libdl code has been unloaded,
resulting in a segfualt at thread cleanup time.

Prevent libdl from unloading to work around TLS destructor bug

---

src/windows/access-helpers.c

Resolves crashing during spin up in Windows Store/Universal app scenarios

Missing execute bit (fixes #67)

---

src/qnx/system-qnx.c

These are processes which appear in /proc, but which you cannot open a /proc/<pid>/as for

Handle zombie processes gracefully

---

lib/agent/agent-container.vala
lib/agent/agent.vala
lib/agent/script-engine.vala
lib/gadget/gadget.vala
lib/gadget/script-engine.vala
lib/interfaces/session.vala
server/server.vala
src/darwin/darwin-host-session.vala
src/darwin/frida-helper-process.vala
src/darwin/frida-helper-types.vala
src/darwin/frida-helper.vala
src/frida.vala
src/host-session-service.vala
src/linux/linux-host-session.vala
src/qnx/qnx-host-session.vala
src/windows/windows-host-session.vala
tests/test-agent.vala

This addresses a long-standing design flaw where each `attach()` request would return the same object, or more precisely, the same shared session. The result was that clients would need to coordinate so that two clients interested in attaching to the same process wouldn't step on each other in case one decided to `detach()` once it was done.

Add support for multiple agent sessions

---

src/darwin/frida-helper-backend-glue.m

Resuming the newly created thread only after dispatch_resume greatly decreases the
probability to miss the DISPATCH_MACH_SEND_DEAD event.

Avoid racing on agent thread creation / monitoring

---

src/darwin/frida-helper-backend-glue.m

- find the libSystem.B.dylib module in memory
- find its initializer (is the only one in __mod_init_func section)
- find the exit point of the initializer by disassembling the function code
- place the breakpoint there
This allows earlier instrumentation than before.

Move hardware breakpoint to libSystem initializer

---

src/darwin/frida-helper-backend-glue.m

- dyld's ImageLoader::recursiveInitialization has a different signature than on following versions of iOS
- improve error handling when that symbol cannot be resolved

Fix regression on iOS 8.4

---

lib/gadget/gadget.vala

This change introduces FRIDA_GADGET_LISTEN_ADDRESS environment variable. If the variable is set, frida-gadget will use it as a listen address. Otherwise the default localhost:27042 is used.
For example, the following makes it listen on any interface:
```
FRIDA_GADGET_LISTEN_ADDRESS="tcp:host=192.168.178.11,port=27042" DYLD_INSERT_LIBRARIES=./build/frida-macos-universal/lib/FridaGadget.dylib ./build/frida-macos-universal/bin/frida-server
```
And then:
```
➜  Desktop netstat -ant | grep 27042
tcp4       0      0  192.168.178.11.27042   *.*                    LISTEN
➜  Desktop
```
This allows using frida-gadget with remote systems (e.g. a linux armhf system) that do not have "USB" support without doing any network/vm-level forwarding.

Add FRIDA_GADGET_LISTEN_ADDRESS environment variable to frida-gadget

---

src/darwin/system-darwin.m
src/system.vala

This way the trash icon can remain empty, so you don't want to always empty it.

On MacOS, create a hidden subdirectory to use for tmp

---

src/darwin/frida-helper-backend-glue.m

- frida/frida#376
- frida/frida#373
- frida/frida#245
- frida/frida#211
- frida/frida-core#159
- frida/frida-core#102
- frida/frida-python#102
Please view the newer iPhoneOS.sdk(e.g. iPhoneOS10.3.sdk) headers and XNU source.
(`iPhoneOS.sdk/usr/include/mach/arm/_structs.h`,  `iPhoneOS.sdk/usr/include/mach/arm/thread_status.h`, [apple/darwin-xnu/blob/master/osfmk/arm/machine_task.c](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/arm/machine_task.c))
_structs.h:
```C
typedef _STRUCT_ARM_DEBUG_STATE32		arm_debug_state32_t;
typedef _STRUCT_ARM_DEBUG_STATE64		arm_debug_state64_t;
/*
* Otherwise not ARM64 kernel and we must preserve legacy ARM definitions of
* arm_debug_state for binary compatability of userland consumers of this file.
*/
#if …
```

Fix legacy iOS 32-bit device(pre-armv8) spawn issue

---

src/linux/frida-helper-service-glue.c

This fixed the arm 32bit processes crashing on android 8(O) after the last release.

fixes the frida agent injection bug on android 8 arm 32bit processes

---

lib/gadget/gadget.vala

Frida gadget looks for a config file with the same name of the lib. In Android, during installation, the files that do not starts with "lib" and do not ends with ".so" are not copied to libs folder. With this workaround the gadget will look to <gadgetname>.config.so instead of <gadgetname>.config
So, if your gadget file name is "libfrida-gadget.so", the gadget will look for "libfrida-gadget.config.so" config file.
(Tested in Android 7.0)

Trick to load .config.so file in ANDROID instead of .config

---

src/darwin/agent/launchd.js
tests/test-agent.vala

rawIdentifier is a little different(tested on iPhone5,2 iOS 10.3.3), take a look at the following.
```
$ frida -U -l launchd.js -p 1
____
/ _  |   Frida 10.6.40 - A world-class dynamic instrumentation framework
| (_| |
> _  |   Commands:
/_/ |_|       help      -> Displays the help system
. . . .       object?   -> Display information about 'object'
. . . .       exit/quit -> Exit
. . . .
. . . .   More info at http://www.frida.re/docs/home/
Attaching... 
[iPhone::PID::1]-> path = /usr/libexec/xpcproxy
rawIdentifier = UIKitApplication:com.google.chrome.ios[0xefd8][64]
path = /usr/libexec/xpcproxy
rawIdentifier = UIKitApplication:com.apple.AppStore[0xc73][64]
path = /usr/libexec/xpcproxy
rawIdentifier = UIKitApplication:com.apple.Preferences[0x4443][64]
```
There is an extra string "[64]", …

Fix iOS 32-bit device (iOS 10) spawn compatibility

---

lib/agent/agent.vala
lib/gadget/gadget.vala

This uses the api changed in https://github.com/frida/frida-gum/pull/268 to cloak more than one range for threads if implemented in the backend.

Potentially cloak multiple ranges from threads

---

lib/gadget/gadget-glue.c
lib/gadget/gadget.vala

- for proper cloaking
- implemented for i/macOS
- as a special entry in apple[] array
- if that’s not present, then fallback to usual behavior

Allow mapped_range to be passed on gadget load()

---

server/server.vala

This is needed because latest vala compiler doesn't keep references automatically.

Keep reference to client alive (WIP)

---

src/linux/frida-helper-service-glue.c

Fixed EMIT_MOV to EMIT_MOVE
This is step one to fixing [#190](https://github.com/frida/frida-core/issues/190)

fixed frida-helper-service-glue typo

---

src/darwin/frida-helper-backend-glue.m
tests/test-host-session.vala

Fix libSystem initialization when DYLD_INSERT_LIBRARIES is there
In this case, `dlopen()` takes a different code path and hits this check in `ImageLoaderMachO::doModInitFunctions()`:
```
if ( ! dyld::gProcessInfo->libSystemInitialized ) {
const char* installPath = getInstallPath();
if ( (installPath == NULL) || (strcmp(installPath, LIBSYSTEM_DYLIB_PATH) != 0) )
dyld::throwf("initializer in image (%s) that does not link with libSystem.dylib\n", this->getPath());
}
```
When we call it to initialize libSystem it throws an exception when loading `libc++.dylib` which is a dependency but it’s not libSystem itself, leaving c++ not initialized and leading to potential crashes.
This solution boils down to hook dyld’s `strcmp()` and make it successful in any case when called from the context of the …

Fix i/macOS libc++ initialization on early instrumentation

---

lib/agent/syscall-linux-mips.S
src/linux/frida-helper-service-glue.c

This fixes the MIPS ASM syntax errors, as well as changing the syntax for struct field access using uclibc. I am not sure if the latter is a overarching issue, but I had issues while trying to compile.

Fix some issues with uclibc and MIPS support

---

src/darwin/frida-helper-backend-glue.m

- simplify the logic, by having a single interface for setting breakpoints and a single place to set the thread and debug states
- implement software breakpoints on iOS versions from 11.3.1 up to and including 11.4.1 where hardware breakpoints are broken in the kernel
- use hardware single step to get out of repeatable breakpoint on all platform, saving a call to capstone
- implement the `getThreadBufferFor_dlerror` helpers function using breakpoints,  needed for iOS 11.3.1
Tested on iOS 9.0.2, 9.3.3, 10.2, 11.1.2, 11.3.1.
According to my tests, the performance of software breakpoints seems about the same as hardware breakpoints.
this should fix https://github.com/frida/frida-core/issues/193

Refactor i/macOS early instrumentation

---

src/linux/frida-helper-service-glue.c

Since binutils 2.31, the options --enable-separate-code is enabled by default for Linux x86 binaries.
(see changelog https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=ld/NEWS;hb=refs/tags/binutils-2_31)
This new version of binutils is the version of last Debian Unstable.
You can still compile your binaries with the option "-z no-separate-code" in gcc, but frida should be able to support this.
This breaks frida on several points I have identified for now:
- Attaching, frida cannot find entry point, because it search for a RX region
- Finding DebugSymbols, but did not find the code that handle this (but probably for the same reason of above). If you could point me the portion of code that handles a simple "DebugSymbol.fromName()" I would be glad to fix it.
- Probably …

[FIX] Fix attach to a ELF with header is only readable

---

src/linux/agent/systemui.js
src/linux/linux-host-session.vala

By specifying the `receiver` and `action` aux options.
Also be as forgiving as the system if the class name is bare and does
not start with a period.
(Based on #212.)

Add support for spawning Android broadcast receivers

---

src/linux/frida-helper-service-glue.c

A lot of rooted Android devices are doing so called "systemless root". One particular example is the Pixel root by Chainfire. In it, the system partition is moved to "system_root", so searching for things like "/system/bin/linker" fails. 
This patch lets Frida work on systemless rooted Android devices.

Adding support for systemless root

---

lib/agent/agent.vala

By calling `thread_suspend` right away without getting locks.

Avoid deadlock when a thread suspends itself

---

server/server.vala

Tested on x86_64 linux
Option `-d` allows for changing the frida-server temporary sub-directory, into which `frida-helper-{32,64}` are dropped, relative to the temporary directory, falling back on the original directory (`re.frida.server`)
```
I   ➤​  ./build/frida-linux-x86_64/bin/frida-server -d FRIDA_TEST
```
Results in:
```
I   ➤​  ls /tmp/FRIDA_TEST                                                                                                                                                       [~/caps/frida]
frida-helper-32*  frida-helper-64*
```

Add frida-server options to specify the temp subdirectory

---

inject/inject.vala

Scenario: i recently bought an android device which needs to do something through injector.
This device for some reason that i don't want to know doesn't allow "setenforce 0" on the stock kernel.
The enforcing selinux doesn't allow frida injector to read files from outside it's context.
An higher level solution wich would bring benefit in other situations would be providing the script source straight to the injector through other ways.
Discussed with the owner both, a base64'd input to avoid issues with \n or an input to the stdin (through outputstream).
I'm gonna use this through an android app which uses Process to run a su -c command to invoke the injector. Tested and working by providing the script to the outputstream
and later by closing it (eof).

frida-inject: read script from stdin if dash is specified

---

lib/agent/agent-glue.c
lib/agent/agent.vala

By replacing them too in `ThreadSuspendMonitor`. This avoids potential deadlocks.

Handle cloaked threads in task_threads and thread_resume

---

meson.build
meson_options.txt

I suggest to make it possible to disable tests (by default, they are built). This will speed up automated builds and allow to skip failing tests (e.g. on linux-arm, cf. issue #190) until they are fixed.

Make it possible to disable tests

---

lib/payload/spawn-monitor.vala

Related to https://github.com/frida/frida/issues/854
Frida didn't have a fallback API to call and it was sending a null address to the upcoming calls. This should fix the problem in older versions of Windows where CreateProcessInternalW is in kernel32.dll and not yet in Kernelbase.dll

Fix CreateProcessInternalW in older windows versions (child_gating)

---

src/darwin/frida-helper-backend-glue.m

by explicitly excluding 12.0 GM to 12.0.1 from the buggy set

Fix iOS buggy kernel check

---

src/darwin/policy-softener-glue.c
src/darwin/policy-softener.vala
src/meson.build

By reimplementing jb_connect, jb_disconnect and jb_entitle_now which apparently are gone in libjailbreak.dylib (the symbols are there but do nothing with success).

Fix spawn on Chimera jailbreak

---

inject/inject.vala
lib/agent/agent-glue.c
lib/agent/agent.vala
lib/gadget/gadget-glue.c
lib/gadget/gadget.vala
lib/interfaces/session.vala
lib/payload/process.vala
lib/payload/script-engine.vala
lib/payload/thread-suspend-monitor.vala
src/api/generate.py
src/frida.vala
tests/test-host-session.vala

The only supported option for now is for explicitly picking a JavaScript
runtime. This means that enable_jit() is now deprecated, but works
better than before as there is no longer any restriction on when it may
be called. All it does now is change the default for scripts created
without specifying which runtime to use.

Add support for specifying script options

---

lib/payload/libc-shim.c

What i'll say it's not confirmed by debugging but just by impressions:
I did worked the whole day hunting some bugs while hooking memcpy.
Before adding memcpy to the shim, the hook on memcpy hit 5/10 threads at once (tested over (50?) times on the same target).
When breakpointed, each thread was calling different frida api (the most used were DebugSymbol.fromAddress and Memory.readByteArray).
After adding the memcpy to the libc-shim, the same proc hit the hook 1/2 times. 
I didn't debugged in the deep if that's really true that some internal frida api uses memcpy so, I would like someone to confirm this in case but from what i get from @oleavr this is safe in any case to be added

added memcpy to libc-shim (1/2)

---

src/darwin/frida-helper-backend-glue.m

- Always set up the fake helpers, as also the latest OSes need them now.
- Fix the ret gadget behavior when used for both helpers and strcmp()
in combination with single-stepping (x86).
This means iOS 12 is now fully supported.
Tested on:

Improve early instrumentation on i/macOS

---

lib/gadget/gadget.vala

The executable name in gadget of android is always 'app_process32' or 'app_process64', and the bundle name is always null. So the feature of script optional configuration in ScriptDirectory mode is not work in android because of the filter will always not match.
I add additional  code for Android to retrieve real executable name and package name, and now android's gadget can work with script optional configuration such as below:
```
{
"filter": {
"executables": ["com.target.app:remote"]
}
}
```
or like:
```
{
"filter": {
"bundles": ["com.target.app"]
}
}
```

Android gadget get executable name and package name

---

inject/inject.vala

My first Vala code, so it might not be vala-thonic
`./frida-inject -p 16920 --script test.js --parameters '{"paramBool": true, "paramArray": [1,2,3], "paramInt": 1, "paramStr": "str", "paramObj": {"a": ["b", "c", {}]}}'`
```
stage early
parameters {"paramBool":true,"paramArray":[1,2,3],"paramInt":1,"paramStr":"str","paramObj":{"a":["b","c",{}]}}
```

Add --parameters to frida-inject to allow specify parameters using a JSON string similar to frida-gadget

---

lib/selinux/src/patch.c

Hi,
When trying to use Frida on a Samsung with Android 9, the **system_server** process dies when trying to launch the server with the following error:
`type=1400 audit(1570464586.875:837): avc:  denied  { map } for  pid=19050 comm="system_server" path="/system/priv-app/tmp_dir/frida-agent-64.so" dev="sda25" ino=5494 scontext=u:r:system_server:s0 tcontext=u:object_r:frida_file:s0 tclass=file permissive=0 audit_filtered`
So i just added the 'map' right to the selinux configuration of the **frida_file** context.
Tested and working on Samsung S10.

Added the 'map' right to the selinux frida_file configuration

---

src/darwin/agent/reportcrash.js

Because in some cases more than one crash can be processed in parallel in different threads.

Split the state by thread id in the ReportCrash agent

---

lib/agent/agent.vala
lib/interfaces/session.vala
src/host-session-service.vala

So that they can be reused for future connections to the same process, avoiding the need to have more than one agent, at least during the lifetime of frida-server.

Keep eternalized entries alive

---

src/darwin/agent/launchd.js
src/darwin/darwin-host-session.vala
src/darwin/frida-helper-backend-glue.m
src/darwin/frida-helper-backend.vala
src/darwin/frida-helper-process.vala
src/darwin/frida-helper-service.vala
src/darwin/frida-helper-types.vala

In this way if frida-server dies it doesn’t leave back unattended pending spawns in a suspended state.

Allow launchd agent to kill pending suspended processes on dispose

---

src/fruity/dtx.vala
src/fruity/fruity-host-session.vala
src/fruity/lockdown.vala

By default the channel is encrypted, unless the service name includes the “?tls=handshake-only” suffix. Internally, the “com.apple.debugserver” and “com.apple.instruments.remoteserver” channels are kept cleartext.

Support both cleartext and encrypted lockdown channels

---

src/darwin/frida-helper-backend-glue.m
src/darwin/frida-helper-process.vala

Modified the flags for when a new process for target and helper is started. 
This way FDs opened by parent are not lost. This only affect MacOS (darwin).
Check [issue](https://github.com/frida/frida-core/issues/269) for additional details.

Fixed #269: Parent file descriptors not available in child process 

---

src/fruity/injector.vala

This makes jailed early instrumentation work on arm64e processes, even when the legacy code path is taken.

Sign helpers callbacks

---

src/fruity/plist.vala
src/fruity/usbmux.vala

* added Plist.from_data to support auto-detecting plist format.
* UsbmuxClient.read_pair_record() supports auto-detecting plist format

Fixes #301 usbmux pair record plist parsing

---

lib/payload/script-engine.vala

Scripts in the LOADING state currently are unable to have messages posted to them. This makes scripts unable to use blocking `recv()` while in their main body. This restriction is unnecessary as LOADING scripts are perfectly capable of receiving messages.
Tested and working with blocking `recv()` in local build.
Fix to issue: https://github.com/frida/frida-gum/issues/420

Relaxed post restriction in LOADING state

---

src/droidy/droidy-host-session.vala

This small change just removes the check for the "tcp:" prefix in open_channel so that other protocols like localabstract, localreserved, etc will work. Droidy.Client.request_protocol_change already handles this appropriately. Now the only check is that the address has the format "%s:%s".

Remove tcp check in android open_channel so that other protocols are supported

---

src/fruity/fruity-host-session.vala

Failing to do so any removed device remains inaccessible until the host process dies.

Fix device removal wiring in the Fruity backend

---

src/fruity/fruity-host-session.vala

This is an alternative simpler solution for the same problem https://github.com/frida/frida-core/pull/329 was attempting to solve.
usbmuxd doesn’t accept any command after starting the listening mode. The “dummy request” we used to flush the device list makes usbmuxd close the connection because the command is received in the wrong state.
To avoid this issue, the new logic is:
- detect if the peer has closed the connection
- in that case reopen it, and send the “dummy
request” on a secondary connection
That should work because usbmuxd handles all clients on a single thread, so by the time the “dummy request” is handled, the entire list of currently connected devices should have been sent.
According to my local tests, performance-wise this is indistinguishable from the previous logic.

Handle control_client closed by usbmuxd

---

src/linux/agent/system-server.js

Set the flag 'FLAG_ACTIVITY_NEW_TASK' for the 'Intent' object before calling 'startActivity'. See https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/ContextImpl.java#955 for the reason why this might occasionally work when the flag is omitted.
Also remove the call to 'setAction', since explicit intents are being used.

Fix starting Android activities when the intent is not automatically found

---

src/fruity/fruity-host-session.vala

To avoid killing via ProcessControl when possible, because apparently that leaves the debug server in a bad state for which killed apps sometimes appear as already running, failing early instrumentation on subsequent spawn attempts.

Kill via LLDB on jailed iOS

---

src/fruity/dtx.vala
src/fruity/fruity-host-session.vala

Sometimes an app extension was returned as the first matched process, just for failing right after with the “Unable to resolve bundle path to bundle ID” exception.

Skip app extensions when searching frontmost app (on Fruity host session)

---

src/meson.build

- The Vala compiler is capable of emitting GIR directly, so g-ir-scanner, etc. are not required
- This is added as an install target as well

Generate GIR by default

---

inject/inject.vala

```bash
frida-inject --development -s test.js -p $PID -P '{"raw_mode": false}'
frida-inject --development -s test.js -p $PID -P '{"raw_mode": true}'
```
```javascript
function make_blue (message) {
var escape = String.fromCharCode(parseInt('033', 8));
var prefix = "[0;34m";
var suffix = "[0m\n";
var blue = `${escape}${prefix}${message.trim()}${escape}${suffix}`
return blue;
}
rpc.exports = {
raw_mode: false,
init (stage, params) {
var stageStr = make_blue (`STAGE > ${stage.trim()}`)
send(['frida:stdout', stageStr]);
var paramsData = make_blue (`PARAMS > ${params.raw_mode}`)
send(['frida:stdout', paramsData]);
this.raw_mode = params.raw_mode;
},
onFridaStdin (message) {
var stdOutData = make_blue (`> ${message.trim()}`)
send(['frida:stdout', `${stdOutData}\r`]);
},
onFridaGetStdInRawMode: …
```

Improve frida-inject to support rawio

---

inject/inject.vala

Having this enabled by default will prevent use cases such as running frida-inject as a background process.
Also, this currently conflicts with the --eternalize option where it is expected that the process will exit after loading the script.

frida-inject: Make the communication with script through stdin optional.

---

src/darwin/agent/launchd.js

By skipping the call to substituted which eventually results in resuming the app too early, only for the PIDs of the apps spawn by Frida.
Needs more testing to find out possible edge cases of this approach, but to my initial tests it fixes the spawn issue on unc0ver 6.x

Support iOS app spawn on unc0ver 6.x

---

src/linux/frida-helper-backend-glue.c

Use the library base address retrieved using dladdr to find the path in /proc/:pid/maps instead of relying on the library path. This is to handle cases where the android environment is running inside a container.
Similarly, when resolving a linker function, use the already resolved linker base address to match the correct line in /proc/:pid/maps

Rework the function address resolution on Android

---

src/fruity/injector.vala

Noticed while debugging other issues that `get_errno_storage` was always NULL, fixed by adding the missing underscore to the mangled symbol name.

Fix ___error symbol name in fruity injector

---

tools/package-server.sh

Procursus-based jailbreaks such as Odyssey, Taurine and odysseyra1n use dash as `/bin/sh`.
The use of bashisms without a `#!/bin/bash` shebang causes it to fail to start/stop frida-server.

Remove bashisms from iOS maintainer scripts

---

lib/pipe/pipe-darwin.c

Update pipe-darwin.c to use bootstrap_strerror instead of mach_error_string for errors coming from bootstrap_look_up.  Currently the error printed every time is "Unknown error code"

Update pipe-darwin.c to use correct error string

---

src/control-service.vala

Route `output`, `child_added`, `child_removed`, `process_crashed` and `uninjected` signals to all control channel peers.

control-service: fix signal wiring

---

src/portal-service.vala

Whenever a session id is unset from PortalService. This avoids both NULL derefereces and leaks.

portal-service: Always remove ClusterNode and ControlChannel sessions

---

src/fruity/injector.vala

Walk the frame pointer once more, in order to get to the actual caller of `libSystem_initializer` instead of stopping in the middle of it.

fruity: Fix spawn on dyld v4 case (jailed iOS 15.x)

---

src/linux/linux-host-session.vala

In case a crash is reported after a Java crash has already been delivered.
E.g. in apps that set their own uncaught exception handler, rendering
uncaught exceptions non-fatal.

Fix use after free in crash delivery

---

src/darwin/agent/launchd.js

Device: iPhone 11 Pro
System: iOS 14.2
Jailbreak: Taurine 1.1.3
When using `frida -U -f xxx.xxx.xxx`, the following error occurs:
```shell
iPhone-11-Pro:~ root# /usr/sbin/frida-server -v
{"type":"error","description":"TypeError: cannot read property 'slot' of undefined","stack":"TypeError: cannot read property 'slot' of undefined\n    at findSubstrateLauncher (/internal-agent.js:243)\n    at applyJailbreakQuirks (/internal-agent.js:152)\n    at <eval> (/internal-agent.js:50)","fileName":"/internal-agent.js","lineNumber":243,"columnNumber":1}
```
It's strange that executing `Module.enumerateImports('/sbin/launchd').filter(imp => imp.name === 'posix_spawn')[0]` on this device doesn't get the corresponding implementation.
This PR simply makes a judgment and bypasses the problem.

Fix "cannot read property 'slot' of undefined" error

---

portal/portal.vala
server/server.vala

The frida-server Application class can now signal success or failure on `ready()` to allow for the daemon's parent to exit on failures.
See:  https://github.com/frida/frida-core/issues/429
Example
```
sunfish:/ # /data/local/tmp/frida-server -D
sunfish:/ # /data/local/tmp/frida-server -D                                                                                                                                        
Unable to start: Could not listen on address 127.0.0.1, port 27042: Error binding to address 127.0.0.1:27042: Address already in use
1|sunfish:/ # 
```

frida-server: Fix daemon parent ready() fail exit

---

lib/base/meson.build

I'm not sure how it worked for others. Maybe when `gioopenssl` is present it also solve the required openssl headers?

Add missing openssl dependency

---

src/linux/frida-helper-process.vala

I'm not too familiar with Vala, but this seems to work
Fixes #447

Rethrow the original error when resume fails inside the error handler

---

src/api/merge.sh

fix build on linux, where `libtool` is empty
fix #453
> merge.sh: Fix ar script: Use addmod for object files
maybe rename to `merge.sh: Fix build on Linux`

merge.sh: Fix ar script: Use addmod for object files

---

server/frida-server.version

This change ensures the `main` symbol in frida-server artifact is retained during build. On non-rooted Android in some contexts one can't execute binaries from various locations but can load them using `dlopen` and other tricks. If a user manages to trigger `dlopen` + `dlsym` they can invoke `main` directly from within the process they are running without further hacks.

Support loading frida-server as shared library

---

lib/payload/thread-suspend-monitor.vala

In this way we're sure this kind of crashes won't happen anymore:
```
Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x00000001bbfee294
Exception Codes: 0x0000000000000002, 0x00000001bbfee294
VM Region Info: 0x1bbfee294 is in 0x1bbfec000-0x1bbff4000;  bytes after start: 8852  bytes before end: 23915
REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
unused shlib __TEXT      1bbb01000-1bbfec000 [ 5036K] r-x/r-x SM=COW  ... this process
--->  __TEXT                   1bbfec000-1bbff4000 [   32K] r-x/rwx SM=COW  ..._kernel.dylib
__TEXT                   1bbff4000-1bbff8000 [   16K] r-x/r-x SM=COW  ..._kernel.dylib
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 10 Bus error: 10
Terminating Process: exc …
```

darwin: Make ThreadSuspendMonitor passthrough if called by Frida

---

src/linux/frida-helper-backend.vala

The regex used in ProcMapsEntry.find_by_path will not match libc.so line when its major number grater then 0xff (eg: 103:04), This will cause ProcMapsEntry.find_by_path to return null, and frida-server fail to start.
reference:
https://www.kernel.org/doc/Documentation/admin-guide/devices.txt
fixed https://github.com/frida/frida/issues/2484

Fix ProcMapsEntry.find_by_path return null

---

src/darwin/agent/launchd.js
src/darwin/frida-helper-backend-glue.m

Since iOS 15, Darwin has the "prewarm" feature for which most frequently used apps are being spawned ahead of time by `dasd` and kept suspended until the user attempts to launch them, in order to save some startup time.
This was in the way of Frida's spawn mechanism because:
- apps launched that way won't be going through launchd when expected, causing a "timeout was reached" error, or more complex race conditions
- Frida needs to spawn a fresh process to ensure early instrumentation
This change addresses these problems by:
- ignoring prewarm spawns from the launchd agent  (but they're still emitted as spawns if spawn gating is enabled)
- killing existing prewarmed apps before attempting to spawn them
The detection of prewarmed apps is done by checking the presence of the …

darwin: Make spawn aware of prewarm

---

meson.build
server/server.vala
src/control-service.vala
src/darwin/darwin-host-session.vala
vapi/config.vapi

When built with external assets, detect when our program's filesystem path has been rebased, and look for frida-agent.dylib accordingly.

server: Support rootless on iOS and tvOS

---

src/linux/frida-helper-backend.vala

We faced some issues when launching a frida-server on a x86_64 box with an old Linux Kernel. The syscalls `process_vm_readv` and `process_vm_writev` exist but are not implemented.
Therefore, using those syscalls fail and the error ENOSYS is returned.
We allow the linux backend to fallback to the slower implementation of  `read_memory`/`write_memory` when it faces this issue.
To avoid reaching this same issue at each call to `read_memory`/`write_memory`, we set the `process_vm_readv/process_vm_writev` function pointers to null to fallback directly to the "unoptimized" path.

Fallback to "slower"  read_memory/write_memory on old Linux kernel

---

src/frida-glue.c

This reverts commit 98e531b97ea5e8305ca3391fdcd29990e87d8cd4.
Before:
```
$ frida-server -h
Usage:
frida [OPTION?]
...
```
```
$ frida-inject -h
Usage:
frida [OPTION?]
...
```
After:
```
$ frida-server -h
Usage:
frida-server [OPTION?]
...
```
```
$ frida-inject -h
Usage:
frida-inject [OPTION?]
...
```
The bug described in https://github.com/frida/frida-core/issues/235#issuecomment-1845825617 was solved in https://github.com/frida/glib/commit/bf2a10211b3d3896943bac2010197b0728a32fac.

Revert "Add g_set_prgname() to frida_init() (#235)"

---

server/frida-server.xcent

Adds  `com.apple.private.amfi.can-load-cdhash` and `com.apple.private.amfi.can-execute-cdhash` entitlements required to remap binaries in memory on iOS 16.

Add entitlements to allow read and execute cdhash

---

tools/package-server-fruity.sh

Fix Frida deb package to spawn frida-server when running on some specific iOS 16 versions (p.e. iOS 16.7.x)

Fix Frida deb package for iOS 16.x

---

lib/payload/thread-suspend-monitor.vala

To extend the `ThreadSuspendMonitor` scope to prevent deadlock scenarios where threads holding the Cloak or the Interceptor lock get suspended.
depends on https://github.com/frida/frida-gum/pull/787

darwin: Take Interceptor and Cloak locks in TSM

---

src/windows/frida-helper-backend-glue.c

This makes Frida injection compatible with more software. In particular, Mozilla Firefox rejects thread startup if the start address is RWX.

windows: Use RW/RX permissions for injection

---

src/fruity/device-monitor-windows.c

Some virtual TUN adapter's FirstUnicastAddress is NULL, such as the Tunnel created by Clash, which will cause frida to crash when listing available devices.

fruity: Fix adapter FirstUnicastAddress is NULL

---

lib/netif/tunnel-interface-observer.vala

This happened on older iOS versions (happened to me on iPhone X on 16.1)
```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes: 0x0000000000000001, 0x0000000000000000
Triggered by Thread:  5
Thread 5 name:  gdbus
Thread 5 Crashed:
0   CoreFoundation                	       0x1968119d0 CFArrayGetCount + 8
1   frida-server                  	       0x104376164 frida_cf_array_iterator_construct + 92
2   frida-server                  	       0x1043779c4 frida_tunnel_interface_observer_handle_interface_changes + 92
3   frida-server                  	       0x104377868 frida_tunnel_interface_observer_real_start + 276
4   frida-server                  	       0x104372030 frida_web_service_do_start_co + 616
5   frida-server …
```

Fix null dereference in frida-server at startup

---

src/linux/frida-helper-backend.vala

This is an attempt to handle the situation where the process has gone away and we're shutting down. I've observed the system looping attempting to move the state out of ATTACHED. It's possible that the state machine here needs to be made more complex (ALREADY_ATTACHED) is misleading.
Informs #478

linux/frida-helper-backend: handle process gone

---

.github/workflows/ci.yml

We were relying on the version built into the image being correct. It is now too new.

.github/workflows: download proper ndk version

---

lib/gadget/gadget.vala
lib/gadget/meson.build
meson.build
vapi/minizip.vapi

On Android, when apps have `extractNativeLibs` set to `false`, the
configuration and potentially script files for frida-gadget are not
extracted and cannot be read using `FileUtils`.

Use maybe_extract_from_apk for Gadget files

---

src/linux/frida-helper-backend.vala

For some target programs it's not reasonable to assume that any hijacked thread has a large stack. For example, in Go, stacks are often small and are allocated on the heap. The injector bootstrap program uses kilobytes of stack. In order to side-step this problem, this patch enables an option to allocate an auxiliary stack for the remote call to use and, for the bootstrapper and loader, uses it.
The calls to mmap and munmap don't use much stack, so they are fine.
Fixes #544

linux: Allocate stack for injector's remote calls

---

compat/build.py

When I was compiling on windows, I got an error
`'utf-8' codec can't decode byte 0x90 in position 2:  invalid start byte"`
I looked at it because my windows system is gbk encoded, which is the encoding on many windows, and the frida-core compiler script is "utf-8" which caused this error, and when I modified it, the compiler worked fine.

Fix Compilation Errors due to Windows Encoding  Issues

---

src/linux/frida-helper-backend.vala

6e3e1cd000-6e3e2c7000 r--s 00000000 07:08 38                             /apex/com.android.runtime/lib64/bionic/libc.so
71eb6c2000-71eb6ff000 r--p 00000000 07:08 38                             /apex/com.android.runtime/lib64/bionic/libc.so
71eb6ff000-71eb781000 r-xp 0003d000 07:08 38                             /apex/com.android.runtime/lib64/bionic/libc.so
71eb781000-71eb786000 r--p 000bf000 07:08 38                             /apex/com.android.runtime/lib64/bionic/libc.so
71eb786000-71eb787000 rw-p 000c3000 07:08 38                             /apex/com.android.runtime/lib64/bionic/libc.so
the first line mapping of the http://libc.so, it's shared , we can't start from it, we need to start from the second line

Need to exclude the "shared" libc.so mapping

---

src/droidy/droidy-client.vala

If more than around 8 devices are connected over ADB, frida doesn't see any ADB connected devices anymore. This fixes the issue (tested for around 40 devices).

Support more than ~8 ADB-connected devices

---

src/fruity/device-monitor.vala

This PR fixes the issues:
* https://github.com/frida/frida/issues/3303
* https://github.com/frida/frida/issues/3278
* https://github.com/frida/frida/issues/3279
* https://github.com/frida/frida/issues/3283
As an Frida USB device with an empty `udid` should not occur with common iOS or Android devices I assume that it is safe to filter out such devices. 
@oleavr

fix iOS error "failed to open USB device: Input/Output Error"

---

src/fruity/network-stack.vala

This change makes sure `pcb.output()` is called even when no more space is available on the queue, preventing stall.

network-stack: Always send enqueued data

---

src/fruity/network-stack.vala

By flagging as writable as soon as some space is available, without waiting for the low watermark.

network-stack: Reduce delay between writes

---

src/darwin/agent/launchd.js

Cleans up old GumJS apis. This specific PR focuses on solving "Attaching..." issue on jailbroken iOS, or more specifically
```
{"type":"error","description":"TypeError: not a function","stack":"TypeError: not a function\n    at findSubstrateLauncher (/internal-agent.js:260)\n    at applyJailbreakQuirks (/internal-agent.js:170)\n    at <eval> (/internal-agent.js:50)","fileName":"/internal-agent.js","lineNumber":260,"columnNumber":1}
```

fix: cleanup old GumJS API reference

---

src/frida.vala

To be robust against scenarios where an out-of-order detach could lead to indefinite hang at release time.

Allow agent sessions to detach before release

---

meson.build
src/compiler/backend-glue.c
src/compiler/build-backend.py
tools/cgo/detect.py

To avoid conflicts when we're linked into a Go binary.

compiler: Rename conflictful Go symbols in backend

---

src/compiler/shims.go

Previously, embeddedShims can only reach source files with maximum depth of 2. Which will result in errors like:
open node_modules/@frida/assert/internal/util/comparisons.js: file does not exist
This update allows matching such files.
I have compiled and tested the modified frida compiler.

compiler: fix error reading shim files

---

meson.build

The vala README only mentions autoconf&make instructions, and when vala is compiled that way the -frida suffix is not added to the version string, and the frida-core check for vala fails.
Therefore, clarify that vala needs to be built from source with meson.
See also complementary PR in vala: https://github.com/frida/vala/pull/7

meson: clarify that frida's vala needs to be built with meson

---

lib/payload/cloak.vala

Closes 
- https://github.com/frida/frida/issues/3535
- https://github.com/frida/frida-core/issues/1133
---
The issue is similar to https://github.com/frida/frida-core/issues/500, where zygote is waiting for a single thread to continue, otherwise it crashes.
For a while this has been changed to use `art::GetOsThreadStat`, so the old fix no longer works.
See android source code for reference:
- https://cs.android.com/android/platform/superproject/main/+/main:art/runtime/runtime.cc;l=779;drc=fc2f6b36c4d23dc70e1b7c2122890bb8ecc9c834
- https://cs.android.com/android/platform/superproject/main/+/main:art/libartbase/base/utils.cc;l=382-404;drc=61197364367c9e404c7da6900658f1b16c42d0da
---
While this does correctly cloak the same as it used to, processes are still hanging sometimes. Zygote no …

WIP: Add support for art::GetOsThreadStat to ThreadCountCloaker

---

lib/base/session-glue.c
lib/base/session.vala
lib/gadget/gadget-darwin.m
server/meson.build
server/server-glue.c
src/darwin/frida-helper-backend-glue.m
src/darwin/policy-softener-glue.c
src/darwin/system-darwin.m
src/embed-agent.py
src/embed-helper.py
src/meson.build
tests/process-resource-usage.c

I’m attempting to compile frida-gadget for visionOS 26. So far, I’ve modified the releng, frida-core, and frida-gum projects and submitted pull requests for them.
Since I’m not very familiar with Vala and Meson, I took a rather straightforward approach by simply adding XROS wherever the IOS macro was used. I also made minor changes to libffi (although I believe a better solution would be to upgrade it).
At the moment, the build completes successfully, and an Xcode visionOS app can also compile without issues. However, the app crashes at runtime. Below is the call stack.
I’m not very familiar with Frida’s internal mechanisms, so I may need some help.
```
dyld`__abort_with_payload:
0x19af9d010 <+0>:  mov    x16, #0x209               ; =521 
0x19af9d014 <+4>:  svc    #0x80
->  0x19af9d018 …
```

platform: add support for VisionOS

---

src/fruity/lockdown.vala

So the error doesn't become persistent, and the device can be paired again.

fruity: Unpair on InvalidHostID
